### ISSUE TITLE
Unnecessary global variables in JS library

### ISSUE THREAD

**Issue by motekaj** [UnifiedPaymentSolutions/everypay-integration#5]
Please use closures/namespacing/some module pattern to expose needed variables and avoid the global declarations in the JS library.

Out of all the declarations, lines 28 and 29 with variables `window_height` and `window_width` carry a higher risk because it is more likely that those names would be used elsewhere in your client's projects for unrelated system functions.

Thanks
Jake Tom

**Comment by borgand** [comment]
Thank you for this reasonable request.

We will put this into the plan and push a fix some time in the future.

**Comment by motekaj** [comment]
You're welcome @borgand, I should make a separate issue for the next challenge I'm facing but since I have your attention at the moment, maybe I can raise it here.

The linkpay form has a serious deficiency. Country field should be a dropdown with a fixed range of values. If any customer places an order on my website and provides a meaningless value, it will slow down my accounting process. Perhaps it's validated on the server but client side validation would nip the issue in the bud and improve UX. Secondly, is there some way to validate VAT field for companies prior to hitting the make payment button?

I'm just raising them as issues that would solve some problems I couldn't find solutions for on the linkpay form - these issues will cost me money if they turn into actual problems. Please keep them in mind for your next updates or let me know if there's another way to achieve the same thing currently.

**Comment by borgand** [comment]
Hi, @motekaj!

We will keep these two suggestions in mind.
We have some ideas to refactor how the custom fields work, but currently no plans to implement these ideas.

For the time being the custom fields don't have types and are treated as text by us and forwarded to the merchant as is. This is because we only gathering data on what types most of the merchants would need and we don't want to tie ourselves prematurely into any specific implementation.

**Comment by motekaj** [comment]
The data-driven decision process is great. But if the country is not right, it will disrupt my VAT calculations at such an early stage. 

My proposal is that a fixed dropdown menu is a reasonably better baseline to work from as you move towards a more sophisticated implementation down the line (based on your merchant data). At least compared to a free text input - and not very time-intensive to implement.

I hope every-pay can consider it for faster implementation or some alternative but regardless, thanks for taking the time to be so responsive to my concerns. I'm really excited for the future growth of everypay products and it's awesome that you're undertaking such an initiative right here in Estonia. This ability to reach you via email or on github is very valuable to me as your client and I understand if this proposal is rejected, I just wanted to put it out there. 

Thanks.
