### ISSUE TITLE
The library lacks licensing information and being available on Packagist

### ISSUE THREAD

**Issue by rimas-kudelis** [UnifiedPaymentSolutions/everypay-integration#9]
Hi!
Is there any reason why this library is not registered on Packagist?
Also, it would be super useful if it had a license file commited to the repository (MIT preferably, although anything is better than nothing).

**Comment by borgand** [comment]
Thank you for pointing out the shortcomings.
This library is for our older API, so we won't be publishing this anywhere anymore, but we will keep the points in mind when we would come up with a new PHP library for newer APIs.
As of now we haven't yet decided to create PHP library, though, as we do support many e-commerce platforms via plugins and all the custom integration needs are hard to address with a single library (this library had quite low usage).

**Comment by rimas-kudelis** [comment]
Thanks. I've noticed as well that the library doesn't seem to match current API. :)
